worker_processes ${{NUM_WORKERS}};
error_log stderr notice;
daemon off;
pid logs/nginx.pid;
env POSTGRES_USER;
env POSTGRES_PASSWORD;
env POSTGRES_DB;
env POSTGRES_HOST;
env DATABASE_URL;

events {
  worker_connections 1024;
}

http {
  include mime.types;

  init_by_lua_block {
    require "lpeg"
  }

  server {
    listen ${{PORT}};
    # https://github.com/leafo/lapis/issues/171#issuecomment-478909564
    resolver 127.0.0.11;
    lua_code_cache ${{CODE_CACHE}};

    # CORS
    location /api/ {
      add_header Access-Control-Allow-Origin '*';
      add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS';
      add_header Access-Control-Allow-Headers 'X-Requested-With, Content-Type, Authorization';
      default_type text/html;
      content_by_lua_block {
        require("lapis").serve("app")
      }
    }

    location /static/ {
      alias static/;
    }

    location /favicon.ico {
      alias static/favicon.ico;
    }

    # Serve the frontend assets
    location /assets/ {
      alias static/assets/;
    }

    # Specify the default index file.
    # index /static/index.html;

    # Serve all requests by trying the file directly; if not found, fallback to index.html.
    location / {
        try_files $uri $uri/ /static/index.html;
    }
  }
}
